name: ServerEvents
main: com.wimbli.serverevents.ServerEvents
version: 1.6.0
commands:
  serverevents:
    description: Primary command for ServerEvents.
    usage:
      - <command> reload - reload data from server_events.xml
      - <command> register - begin registration with Twitter
permissions:
  serverevents.reload:
    description: Ability to make the plugin reload data from server_events.xml, using /serverevents reload
    default: op
  serverevents.register:
    description: Ability to register with a Twitter account, using /serverevents register
    default: op
